// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNQzj7xEciDOH9WICXzYxfpNllxvIXXag',
    appId: '1:521840446802:web:ce9167d1981d6ee9a2fe8b',
    messagingSenderId: '521840446802',
    projectId: 'pharmai-c7d09',
    authDomain: 'pharmai-c7d09.firebaseapp.com',
    storageBucket: 'pharmai-c7d09.firebasestorage.app',
    measurementId: 'G-JJFF50RZ1K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi6EblmMkHkXCwPQEE2f21M5S_Psy5T94',
    appId: '1:521840446802:android:fad5e82f09a7b394a2fe8b',
    messagingSenderId: '521840446802',
    projectId: 'pharmai-c7d09',
    storageBucket: 'pharmai-c7d09.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8pqJvU_iQTZ9PPUu6aApRrqVpdFWvTn0',
    appId: '1:521840446802:ios:a599330ea43da9d7a2fe8b',
    messagingSenderId: '521840446802',
    projectId: 'pharmai-c7d09',
    storageBucket: 'pharmai-c7d09.firebasestorage.app',
    androidClientId: '521840446802-6eekf258qflhm7er2sj048iblcelkt1f.apps.googleusercontent.com',
    iosClientId: '521840446802-955eqqv1p0nqdjqmm2eqam449fct2132.apps.googleusercontent.com',
    iosBundleId: 'com.kiraathanelabs.pharmai',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8pqJvU_iQTZ9PPUu6aApRrqVpdFWvTn0',
    appId: '1:521840446802:ios:a599330ea43da9d7a2fe8b',
    messagingSenderId: '521840446802',
    projectId: 'pharmai-c7d09',
    storageBucket: 'pharmai-c7d09.firebasestorage.app',
    androidClientId: '521840446802-6eekf258qflhm7er2sj048iblcelkt1f.apps.googleusercontent.com',
    iosClientId: '521840446802-955eqqv1p0nqdjqmm2eqam449fct2132.apps.googleusercontent.com',
    iosBundleId: 'com.kiraathanelabs.pharmai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNQzj7xEciDOH9WICXzYxfpNllxvIXXag',
    appId: '1:521840446802:web:31107d05ba77f277a2fe8b',
    messagingSenderId: '521840446802',
    projectId: 'pharmai-c7d09',
    authDomain: 'pharmai-c7d09.firebaseapp.com',
    storageBucket: 'pharmai-c7d09.firebasestorage.app',
    measurementId: 'G-E18S6STK4B',
  );
}
